sudo: required

services:
  - docker

env:
  - VERSION=0.67.2 RUBY=2.5
  - VERSION=0.11.1 RUBY=2.5

script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build --build-arg version=$VERSION -t udalov/rubocop:$VERSION -f Dockerfile.ruby-$RUBY .

  - if [ "$TRAVIS_BRANCH" == "master" ]; then docker push udalov/rubocop:$VERSION; fi
