sudo: required

services:
  - docker

before_install:
  - docker -v

script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -f Dockerfile.dev -t rubocop-in-docker-dev .
    export VERSION=`docker run rubocop-in-docker-dev`
    docker build --build-arg version=$VERSION -t udalov/rubocop:$VERSION .
  fi
