sudo: required

services:
  - docker

script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    docker build -t udalov/rubocop:latest -f Dockerfile.latest .;
    export VERSION=`docker run -it udalov/rubocop:latest rubocop -v | tr -d '\r'`;

  - docker pull udalov/rubocop:$VERSION || true
  - docker build --cache-from udalov/rubocop:$VERSION --build-arg version=$VERSION -t udalov/rubocop:$VERSION -f Dockerfile .

  - docker run -it udalov/rubocop:$VERSION rubocop -v
  - docker run -v "$PWD:/app" -it udalov/rubocop:$VERSION rubocop test/test.rb

  - if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker push udalov/rubocop:latest;
        docker push udalov/rubocop:$VERSION;
    fi
