sudo: required

services:
  - docker

before_install:
  - docker -v

script:
  - docker build -f Dockerfile.dev -t rubocop-in-docker-dev .
  - export VERSION=`docker run rubocop-in-docker-dev`

  - 'if [ "$TRAVIS_TAG" != "" ]; then
      export VERSION=$TRAVIS_TAG;
    fi'

  - 'if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker build --build-arg version=$VERSION -t udalov/rubocop:$VERSION -t udalov/rubocop:latest . ;
    fi'
