sudo: required

services:
  - docker

env:
  - VERSION=0.1.0 RUBY=2.0
  # - VERSION=0.11.0 RUBY=2.5
  # - VERSION=0.11.1 RUBY=2.5
  # - VERSION=0.12.0 RUBY=2.5
  # - VERSION=0.13.0 RUBY=2.5
  # - VERSION=0.13.1 RUBY=2.5
  # - VERSION=0.14.0 RUBY=2.5
  # - VERSION=0.14.1 RUBY=2.5
  # - VERSION=0.15.0 RUBY=2.5
  # - VERSION=0.16.0 RUBY=2.5
  # - VERSION=0.17.0 RUBY=2.5
  # - VERSION=0.18.0 RUBY=2.5
  # - VERSION=0.18.1 RUBY=2.5
  # - VERSION=0.19.0 RUBY=2.5
  # - VERSION=0.19.1 RUBY=2.5
  # - VERSION=0.2.0 RUBY=2.5
  # - VERSION=0.2.1 RUBY=2.5
  # - VERSION=0.20.0 RUBY=2.5
  # - VERSION=0.20.1 RUBY=2.5
  # - VERSION=0.21.0 RUBY=2.5
  # - VERSION=0.22.0 RUBY=2.5
  # - VERSION=0.23.0 RUBY=2.5
  # - VERSION=0.24.0 RUBY=2.5
  # - VERSION=0.24.1 RUBY=2.5
  # - VERSION=0.25.0 RUBY=2.5
  # - VERSION=0.26.0 RUBY=2.5
  # - VERSION=0.26.1 RUBY=2.5
  # - VERSION=0.27.0 RUBY=2.5
  # - VERSION=0.27.1 RUBY=2.5
  # - VERSION=0.28.0 RUBY=2.5
  # - VERSION=0.29.0 RUBY=2.5
  # - VERSION=0.29.1 RUBY=2.5
  # - VERSION=0.3.0 RUBY=2.5
  # - VERSION=0.3.1 RUBY=2.5
  # - VERSION=0.3.2 RUBY=2.5
  # - VERSION=0.30.0 RUBY=2.5
  # - VERSION=0.30.1 RUBY=2.5
  # - VERSION=0.31.0 RUBY=2.5
  # - VERSION=0.32.0 RUBY=2.5
  # - VERSION=0.32.1 RUBY=2.5
  # - VERSION=0.33.0 RUBY=2.5
  # - VERSION=0.34.0 RUBY=2.5
  # - VERSION=0.34.1 RUBY=2.5
  # - VERSION=0.34.2 RUBY=2.5
  # - VERSION=0.35.0 RUBY=2.5
  # - VERSION=0.35.1 RUBY=2.5
  # - VERSION=0.36.0 RUBY=2.5
  # - VERSION=0.37.0 RUBY=2.5
  # - VERSION=0.37.1 RUBY=2.5
  # - VERSION=0.37.2 RUBY=2.5
  # - VERSION=0.38.0 RUBY=2.5
  # - VERSION=0.39.0 RUBY=2.5
  # - VERSION=0.4.0 RUBY=2.5
  # - VERSION=0.4.1 RUBY=2.5
  # - VERSION=0.4.2 RUBY=2.5
  # - VERSION=0.4.3 RUBY=2.5
  # - VERSION=0.4.4 RUBY=2.5
  # - VERSION=0.4.5 RUBY=2.5
  # - VERSION=0.4.6 RUBY=2.5
  # - VERSION=0.40.0 RUBY=2.5
  # - VERSION=0.41.0 RUBY=2.5
  # - VERSION=0.41.1 RUBY=2.5
  # - VERSION=0.41.2 RUBY=2.5
  # - VERSION=0.42.0 RUBY=2.5
  # - VERSION=0.43.0 RUBY=2.5
  # - VERSION=0.44.0 RUBY=2.5
  # - VERSION=0.44.1 RUBY=2.5
  # - VERSION=0.45.0 RUBY=2.5
  # - VERSION=0.46.0 RUBY=2.5
  # - VERSION=0.47.0 RUBY=2.5
  # - VERSION=0.47.1 RUBY=2.5
  # - VERSION=0.48.0 RUBY=2.5
  # - VERSION=0.48.1 RUBY=2.5
  # - VERSION=0.49.0 RUBY=2.5
  # - VERSION=0.49.1 RUBY=2.5
  # - VERSION=0.5.0 RUBY=2.5
  # - VERSION=0.50.0 RUBY=2.5
  # - VERSION=0.51.0 RUBY=2.5
  # - VERSION=0.52.0 RUBY=2.5
  # - VERSION=0.52.1 RUBY=2.5
  # - VERSION=0.53.0 RUBY=2.5
  # - VERSION=0.54.0 RUBY=2.5
  # - VERSION=0.55.0 RUBY=2.5
  # - VERSION=0.56.0 RUBY=2.5
  # - VERSION=0.57.0 RUBY=2.5
  # - VERSION=0.57.1 RUBY=2.5
  # - VERSION=0.57.2 RUBY=2.5
  # - VERSION=0.58.0 RUBY=2.5
  # - VERSION=0.58.1 RUBY=2.5
  # - VERSION=0.58.2 RUBY=2.5
  # - VERSION=0.59.0 RUBY=2.5
  # - VERSION=0.59.1 RUBY=2.5
  # - VERSION=0.59.2 RUBY=2.5
  # - VERSION=0.6.0 RUBY=2.5
  # - VERSION=0.6.1 RUBY=2.5
  # - VERSION=0.60.0 RUBY=2.5
  # - VERSION=0.61.0 RUBY=2.5
  # - VERSION=0.61.1 RUBY=2.5
  # - VERSION=0.62.0 RUBY=2.5
  # - VERSION=0.63.0 RUBY=2.5
  # - VERSION=0.63.1 RUBY=2.5
  # - VERSION=0.64.0 RUBY=2.5
  # - VERSION=0.65.0 RUBY=2.5
  # - VERSION=0.66.0 RUBY=2.5
  # - VERSION=0.67.1 RUBY=2.5
  # - VERSION=0.67.2 RUBY=2.5
  # - VERSION=0.68.0 RUBY=2.5
  # - VERSION=0.68.1 RUBY=2.5
  # - VERSION=0.69.0 RUBY=2.5
  # - VERSION=0.7.0 RUBY=2.5
  # - VERSION=0.7.1 RUBY=2.5
  # - VERSION=0.7.2 RUBY=2.5
  # - VERSION=0.70.0 RUBY=2.5
  # - VERSION=0.71.0 RUBY=2.5
  # - VERSION=0.72.0 RUBY=2.5
  # - VERSION=0.73.0 RUBY=2.5
  # - VERSION=0.75.0 RUBY=2.5
  # - VERSION=0.75.1 RUBY=2.5
  # - VERSION=0.8.0 RUBY=2.5
  # - VERSION=0.8.1 RUBY=2.5
  # - VERSION=0.8.2 RUBY=2.5
  # - VERSION=0.8.3 RUBY=2.5
  # - VERSION=0.9.0 RUBY=2.5
  # - VERSION=0.9.1 RUBY=2.5

script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build --build-arg version=$VERSION -t udalov/rubocop:$VERSION -f Dockerfile.ruby-$RUBY .

  - if [ "$TRAVIS_BRANCH" == "master" ]; then docker push udalov/rubocop:$VERSION; fi
